### ISSUE TITLE
Possible conection error

### ISSUE THREAD

**Issue by rfenossi** [junichi11/netbeans-backlog-plugin#22]
Hi junichi i have this error when i try to connect to my space
![backlog netbeans connector error](https://cloud.githubusercontent.com/assets/483095/6993812/4b8cf918-dad7-11e4-96a6-3f0c5d9081c7.png)
Thanks for this great support plugin

**Comment by junichi11** [comment]
Hi @rfenossi ,

It seems to be wrong Space ID.
Space ID is not URL but ID (in your case, Space ID is nonet)

HTH,
Junichi

**Comment by junichi11** [comment]
@rfenossi Were you able to add a repository?

**Comment by rfenossi** [comment]
@junichi11 yes i am using and working with my first repo with the netbeans connector

**Comment by junichi11** [comment]
@rfenossi You're welcome :)
