### ISSUE TITLE
Cannot connect to backlog space from netbeans

### ISSUE THREAD

**Issue by orvie** [junichi11/netbeans-backlog-plugin#23]
As you can see, i've created a  free account on backlog,
and then i generated a new API key on tap ("Personal Settings") 
After that i open my netbeans IDE 8.0.2, clic on task window,
previously i've installed backlog plug-in from netbeans IDE directly.
Select Backlog, as you see on the image, insert the space ID and copy and paste the key from backlog, but i get this error.

I hope you can help me.

Thanks!

![image](https://cloud.githubusercontent.com/assets/12677863/7899822/8ae3ad34-06f9-11e5-8f07-1e5a202252e4.png)

**Comment by junichi11** [comment]
@orvie Probably, Space ID or Api  Key are wrong. Space ID is not user name and url. Space id is `your_space_id` if your project url is the following: https://your_space_id.backlogtool.com  

Could you check it again?

**Comment by orvie** [comment]
Look how i do it, i copy the API Key directly, if you prefer create an account only for test i´ve created at least 2 o 3 times a space and the same problem.

Thanks you, for your help!

![image](https://cloud.githubusercontent.com/assets/12677863/7903654/bd4a076e-07a8-11e5-8ec3-c2971b4f8de9.png)

![image](https://cloud.githubusercontent.com/assets/12677863/7903648/9e39c990-07a8-11e5-9f23-867dde44ecdc.png)

**Comment by junichi11** [comment]
I looked at backlog api error document. 
Code 11 means the following:
> 11: AuthenticationError
> If you are not registered on a target space.

I'll try to create a new account.

**Comment by junichi11** [comment]
Sorry, I found the cause. I'll fix it. So please wait a while...

Thanks for catching it!

**Comment by junichi11** [comment]
@orvie I've fixed it. Could you try to test it (version 0.2.1.1-dev)?
https://github.com/junichi11/netbeans-backlog-plugin/releases/tag/v0.2.1 

I'll release a new nbm as version 0.3.0.

Thanks.

**Comment by junichi11** [comment]
#### NOTE
Please select a your backlog domain in the Backlog ComboBox.

**Comment by junichi11** [comment]
Added fixes for existing repositories in version 0.2.1.2

**Comment by orvie** [comment]
Hi, i've tested version 0.2.1.1 dev and get this error:

![image](https://cloud.githubusercontent.com/assets/12677863/7914121/a401eaf0-083a-11e5-89ce-205eae83c005.png)

**Comment by orvie** [comment]
The same error in version 0.2.1.2

![image](https://cloud.githubusercontent.com/assets/12677863/7914455/a8170aa6-083c-11e5-88bd-a2ea21dfa586.png)

**Comment by junichi11** [comment]
Umm, I can't reproduce it in my environment... (Linux and Windows)

Product Version: NetBeans IDE 8.0.2 (Build 201411181905)
Java: 1.7.0_40; Java HotSpot(TM) 64-Bit Server VM 24.0-b56
Runtime: Java(TM) SE Runtime Environment 1.7.0_40-b43
System: Windows 7 version 6.1 running on amd64; MS932;

**Comment by orvie** [comment]
![image](https://cloud.githubusercontent.com/assets/12677863/7918698/f427cfc2-0858-11e5-9a3c-5627b9e191f6.png)

**Comment by orvie** [comment]
I got it, the problem is the proxy.

Thanks for you help, i will start to use it, then i send you a comment if anything go wrong.!

![image](https://cloud.githubusercontent.com/assets/12677863/7918843/f2c3287e-0859-11e5-8fbc-ea5822008b9f.png)

**Comment by junichi11** [comment]
> I got it, the problem is the proxy.

:+1: 

Thanks for your confirmation!
