### ISSUE TITLE
Bad url task redirection for (Show in Browser)

### ISSUE THREAD

**Issue by rfenossi** [junichi11/netbeans-backlog-plugin#24]
I am in backlogtool.com, i am set my project in the dot com web, but when i click to open my proyect in the browser its redirect to the https://id.backlog.jp/view/myproyect-1 site and them it go for home backlog.jp. Thanks
![untitled-1](https://cloud.githubusercontent.com/assets/483095/8603977/0fba9df2-2652-11e5-8fdc-d07337ce8ac5.jpg)

**Comment by junichi11** [comment]
Thanks for reporting it!
I'll fix it.

**Comment by junichi11** [comment]
@rfenossi I've fixed. Could you try to test it ?

https://github.com/junichi11/netbeans-backlog-plugin/releases/tag/v0.3.0 (0.3.0.1-dev)

Thanks.

**Comment by rfenossi** [comment]
@junichi11 its working correctly, thanks!

**Comment by junichi11** [comment]
:+1:
