### ISSUE TITLE
Deadlock when attaching files on the issue pannel

### ISSUE THREAD

**Issue by DrSchranz** [junichi11/netbeans-backlog-plugin#32]
Netbeans stops responding when opening the file dialog to attach files on the issue panel.

Steps to reproduce:
1 - Open an issue.
2 - Click attach files.

Actual results:
Netbeans stops responding and forced termination is required.

Expected results:
See a file chooser dialog, and proceed with the attachment process.

Plugin version:
0.3.2

Netbeans version:
8.0.2 ( OSX 10.9.5 )

**Comment by junichi11** [comment]
I've created a new nbm for this.

https://github.com/junichi11/netbeans-backlog-plugin/releases/tag/v0.3.3
