### ISSUE TITLE
No Category, No Version, e.t.c. options are not applied in saved queries

### ISSUE THREAD

**Issue by DrSchranz** [junichi11/netbeans-backlog-plugin#36]
#### Overview description
No Category, No Version, e.t.c. options, are not applied on the saved queries in the Tasks window.

#### Steps to reproduce
1. Create a new query from the tasks window.
2. Filter issues with the No Resolution option.
3. Save the query, refresh Tasks window.

#### Actual results
Tasks window results differs from QueryPanel results when using No Category, No Version ... options.

#### Expected results
Same results on both, QueryPanel and Tasks window

#### Version number of the plugin
0.3.3

#### Version information of NetBeans
8.0.2

**Comment by junichi11** [comment]
Thanks for reporting it!
Fixed.

**Comment by junichi11** [comment]
I've created a new nbm for testing.
https://github.com/junichi11/netbeans-backlog-plugin/releases/tag/v0.3.3 0.3.3.1-dev

**Comment by DrSchranz** [comment]
I've tested some cases and now I see the expected results with 0.3.3.1-dev
Thanks for fixing it!
