### ISSUE TITLE
Priority Status Options in Japanese

### ISSUE THREAD

**Issue by marcelboere** [junichi11/netbeans-backlog-plugin#44]
Netbeans 11.2: On the backlog detail tab, second section (attributes) , right part under Priority: the dropdown for status shows Japanese text, while the rest is in English..

**Comment by junichi11** [comment]
Could you please attach a screenshot if possible?

**Comment by marcelboere** [comment]
Of course, the same values are used in the query tab..
![backlog_item_japanese](https://user-images.githubusercontent.com/16916877/69196987-65a6fe00-0b30-11ea-97d9-1b8628126574.jpg)
![backlog_query_japanese](https://user-images.githubusercontent.com/16916877/69196995-6c357580-0b30-11ea-81ba-24e624701547.jpg)

**Comment by junichi11** [comment]
Thank you!

I can reproduce it. But maybe, this problem is the API side, I guess because the plugin just gets the status via the API...

**Comment by junichi11** [comment]
@marcelboere 
I've asked the backlog support about it.(https://twitter.com/junichi_11/status/1196962974134484992) It is an API's problem. I'll let you know when it is fixed. Thanks.

**Comment by junichi11** [comment]
@marcelboere 
This should be OK now.
![nb-backlog-issue-44](https://user-images.githubusercontent.com/738383/69723049-eaf76780-115b-11ea-857c-905242f2439e.png)

Thanks.

**Comment by marcelboere** [comment]
Thank you, I will test soon :). Great those Twitter translate option :)

Have a nice day,
Marcel.

Op wo 27 nov. 2019 13:22 schreef Junichi Yamamoto <notifications@github.com
